# Generated by Django 4.0.3 on 2022-03-18 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_methods',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('deliveryMethod', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Delivery_methods',
            },
        ),
        migrations.CreateModel(
            name='Payment_methods',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('paymentMethod', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Payment_methods',
            },
        ),
        migrations.CreateModel(
            name='Product_categories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Product_categories',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('token', models.TextField()),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Vouchers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('discout', models.FloatField()),
                ('isActive', models.BooleanField()),
            ],
            options={
                'db_table': 'Vouchers',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('imagePath', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('id_productCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiserver.product_categories')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zipCode', models.IntegerField()),
                ('cardNumber', models.IntegerField()),
                ('cardExpirationDate', models.CharField(max_length=50)),
                ('cardCSV', models.IntegerField()),
                ('finished', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id_deliveryMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiserver.delivery_methods')),
                ('id_paymentMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiserver.payment_methods')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiserver.users')),
                ('id_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiserver.vouchers')),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Order_items',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiserver.orders')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiserver.products')),
            ],
            options={
                'db_table': 'Order_items',
            },
        ),
    ]
