# Generated by Django 4.0.3 on 2022-03-19 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_methods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deliverymethod', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'delivery_methods',
            },
        ),
        migrations.CreateModel(
            name='payment_methods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paymentmethod', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='product_categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'product_categories',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastName', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phonenumber', models.CharField(blank=True, max_length=50, null=True)),
                ('token', models.TextField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='vouchers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('discount', models.FloatField()),
                ('isactive', models.BooleanField()),
            ],
            options={
                'db_table': 'vouchers',
            },
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('imagepath', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('id_productcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiserver.product_categories')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('cardnumber', models.IntegerField()),
                ('cardexpirationdate', models.CharField(max_length=50)),
                ('cardcsv', models.IntegerField()),
                ('finished', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id_deliverymethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiserver.delivery_methods')),
                ('id_paymentmethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiserver.payment_methods')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiserver.users')),
                ('id_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiserver.vouchers')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='order_items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiserver.orders')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiserver.products')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
    ]
