# Generated by Django 4.0.3 on 2022-03-28 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='imagepath',
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiserver.vouchers'),
        ),
    ]
