# Generated by Django 4.0.3 on 2022-03-18 22:53

from django.db import migrations
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery_methods',
            options={'managed': sqlalchemy.sql.expression.false},
        ),
        migrations.AlterModelOptions(
            name='order_items',
            options={'managed': sqlalchemy.sql.expression.false},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'managed': sqlalchemy.sql.expression.false},
        ),
        migrations.AlterModelOptions(
            name='payment_methods',
            options={'managed': sqlalchemy.sql.expression.false},
        ),
        migrations.AlterModelOptions(
            name='product_categories',
            options={'managed': sqlalchemy.sql.expression.false},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': sqlalchemy.sql.expression.false},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': sqlalchemy.sql.expression.false},
        ),
        migrations.AlterModelOptions(
            name='vouchers',
            options={'managed': sqlalchemy.sql.expression.false},
        ),
    ]
