# Generated by Django 4.0.3 on 2022-03-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='isadmin',
            field=models.BooleanField(default=False),
        ),
    ]
