# Generated by Django 4.0.3 on 2022-03-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0003_alter_users_email_alter_users_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_methods',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment_methods',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product_categories',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
